micronaut:
  application:
    name: motorcycleStore
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSI

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bikestore
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - "com.felipepossari.motorcyclestore.application.entity"

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bikestore
      user: postgres
      password: 123456
      schemas: bikestore
      default-schema: bikestore